ajax2/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('',
    url(r'^$', 'ajax2.views.list_record', name='list-record'),
    url(r'^(?P<pk>\d+)/$', 'ajax2.views.get_record', name='view-record'),
    url(r'^(?P<pk>\d+)/save/$', 'ajax2.views.save_record', name='save-record'),
    url(r'^ng/$', 'ajax2.views.ng_way', name='ng-way'),
    url(r'^ng/blogs/$', 'ajax2.views.blogs', name='ng-blogs'),
)    

dj_demo_proj/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dj_demo_proj.views.home', name='home'),
    # url(r'^dj_demo_proj/', include('dj_demo_proj.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^polls/', include('polls.urls', namespace='sstar')),
    url(r'^ajax/', include('ajax_demo.urls', namespace='ajax-demo')),
    
    url(r'^ajax2/', include('ajax2.urls', namespace='ajax2')),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    
)

polls/urls.py
from django.conf.urls import url, patterns

#from polls import views

if 0:
    urlpatterns = patterns('polls.views',
        url(r'^$', 'index', name='index'),
        url(r'^(?P<poll_id>\d+)/$', 'detail', name='detail'),
        url(r'^(?P<poll_id>\d+)/result/$', 'result', name='result'),
        url(r'^(?P<poll_id>\d+)/vote/$', 'vote', name='vote'),    
    )
if 1:
    from polls import views
    urlpatterns = patterns('polls.views',
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
        url(r'^(?P<pk>\d+)/result/$', views.ResultView.as_view(), name='result'),
        url(r'^(?P<poll_id>\d+)/vote/$', 'vote', name='vote'),    
    )

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published date')
    
    def __unicode__(self):
        return self.question
        
    def was_published_recently(self):
        return self.pub_date > timezone.now() - datetime.timedelta(hours=2)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'recently published?'
        

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return u'%s > %s' % (self.poll.question, self.choice_text)
        
        

polls/views.py
# Create your views here.
from django.http import HttpResponse


from polls.models import Poll, Choice

from django.template import RequestContext, loader
def index(request):
    """
    use template loader and RequestContext to render template
    """
    filters = {'question__contains': 'xx'}
    filters = {}
    
    polls = Poll.objects.order_by('-pub_date')
    if filters:
        polls = polls.filter(**filters)

    #create context and let template render the context
    context = RequestContext(request, {'who': 'john', 'polls': polls})
    tpl = loader.get_template('polls/index.html')
    
    return HttpResponse(tpl.render(context))

from django.shortcuts import render, get_object_or_404
from django.http import Http404    
def detail(request, poll_id):
    """
        use shortcut : render - combine HttpResponse, RequestContext, template loading all together
    """
    
    #
    # short and short cut
    #
    context = {'poll': get_object_or_404(Poll, pk=poll_id)}
    return render(request, 'polls/detail.html', context)
    
    #
    # short cut
    #
    try:
        dtl = Poll.objects.get(pk=poll_id)
        context = {'poll': dtl}        
    except Poll.DoesNotExist:
        raise Http404
        
    return render(request, 'polls/detail.html', context)
    
def result(request, poll_id):
    context = {'poll': Poll.objects.get(pk=poll_id)}
    return render(request, 'polls/result.html', context)
   
from django.http import HttpResponseRedirect   
from django.core.urlresolvers import reverse
def vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    
    choice = request.POST.get('choice', None)
    if choice is None:
        return render(request, 'polls/detail.html', {'poll': poll, 'error_msg': 'Please make a selection'})
    
    #ch = Choice.objects.get(pk=choice)
    ch = poll.choice_set.get(pk=choice)
    ch.votes +=1
    ch.save()
    
    return HttpResponseRedirect(reverse('sstar:result', args=(poll_id, )))
    
    
#
# generic view - pattern for common record detail -> action -> redirect result -> list
#
# - don't see much merits, kind of silly and only good for single record or drill down thing
#
#
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'polls'
    
    def get_queryset(self):
        return Poll.objects.order_by('-pub_date')[:10]
        
class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

class ResultView(generic.DetailView):
    model = Poll
    template_name = 'polls/result.html'
    
    

polls/templates/polls/base.html
{% load staticfiles %}
<html>
<head>
<link type="text/css" rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
<h1> polls </h1>
<div id="content">
{% block contentmain %}
main content data goes here
{% endblock %}
</div>

<h1> end of polls</h1>
</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block contentmain %}
<h2>{{poll.question}}</h2>
{{ poll.pub_date }}
{% if error_msg %}<p style="color:red;"><b>{{ error_msg }}</b></p>{% endif %}

<form action="{% url 'sstar:vote' poll.id %}" method="post">
{% csrf_token %}
<ul>
    {% for choice in poll.choice_set.all %}
        <li><input type="radio" name="choice" id="choice-{{ choice.id }}" value="{{ choice.id }}">
            <label for="choice-{{ choice.id }}">{{ choice.choice_text }} </label>
        </li>
    {% endfor %}
</ul>
<input type="submit" value="Vote to see results">
</form>

{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block contentmain %}

{% if polls %}
    <ul>
    {% for p in polls %}
        <li><a href="{% url 'sstar:detail' p.id %}">{{ p.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <b>no polls</b>
{% endif %}


{% endblock %}

polls/templates/polls/result.html
{% extends "polls/base.html" %}
{% block contentmain %}
<h2>{{poll.question}}</h2>
<p>{{ poll.pub_date }}</p>

<br/>

    {% for choice in poll.choice_set.all %}
        {{ choice.choice_text }}: {{ choice.votes }} vote{{ choice.votes|pluralize }} <br/>
    {% endfor %}
<p><a href="{% url 'sstar:detail' poll.id %}">Vote Again?</a></p>
{% endblock %}