ajax2/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('',
    url(r'^$', 'ajax2.views.list_record', name='list-record'),
    url(r'^(?P<pk>\d+)/$', 'ajax2.views.get_record', name='view-record'),
    url(r'^(?P<pk>\d+)/save/$', 'ajax2.views.save_record', name='save-record'),
    url(r'^ng/$', 'ajax2.views.ng_way', name='ng-way'),
    url(r'^ng/blogs/$', 'ajax2.views.blogs', name='ng-blogs'),
)    

dj_demo_proj/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dj_demo_proj.views.home', name='home'),
    # url(r'^dj_demo_proj/', include('dj_demo_proj.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^polls/', include('polls.urls', namespace='sstar')),
    url(r'^ajax/', include('ajax_demo.urls', namespace='ajax-demo')),
    
    url(r'^ajax2/', include('ajax2.urls', namespace='ajax2')),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    
)

ajax2/models.py
from django.db import models

# Create your models here.

class SillyBlog(models.Model):
    subject = models.CharField(max_length=60)
    body = models.TextField(null=False, blank=False)
    
    def __unicode(self):
        return self.subject
        

ajax2/views.py
# Create your views here.

#http://django-tastypie.readthedocs.org/en/latest/authorization.html#usage

from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render_to_response, render
from django.core.urlresolvers import reverse
from rest_framework import parsers, renderers, serializers
from rest_framework.response import Response

from ajax2.models import SillyBlog

#
# django + angular
#
def ng_way(request):
    records = api_list_records(request)
    serializer = SillyBlogSerializer(records, many=True)
    
    json = renderers.JSONRenderer().render(serializer.data)
    
    context = {'records': json}
    
    context = {}
    return render(request, 'ajax2/ng.html', context)

    
#
# django + jQuery + ajax
#

#
# HTTP request
#
def list_record(request):
    records = api_list_records(request)    
    context = {'records': records}
    return render(request, 'ajax2/records.html', context)

def blogs(request):
    records = api_list_records(request)
    data=SillyBlogSerializer(records).data
    return _response(request, data)
    
def get_record(request, pk): 
    blog = api_new_record if pk == '0' else api_get_record(pk)        
    context = {'blog': blog}
    return render(request, 'ajax2/editor.html', context) 
        
def save_record(request, *args, **kwargs):
    if request.method != 'POST':
        raise HttpResponseForbidden()
        
    pk = kwargs.get('pk', '')        
    blog = api_get_record(pk)
    
    #
    # RULE - allow vs exclude - data access rules on FIELD level
    #
    allow = ['subject', 'body']
    exclude = ['creator_account', 'owner_account']
    data = {}
    for field in allow:
        if field in request.POST:
            data[field] = request.POST[field]
    
    resp_data = api_save_record(blog, data) or SillyBlogSerializer(blog).data
    return _response(request, resp_data)

#
# let rest_framework handle HTTP negotiation and data exchange
#        
from rest_framework.decorators import api_view

@api_view(['GET', 'POST']) 
def _response(request, data):
    return Response(data)

#
# serializers
#    
class SillyBlogSerializer(serializers.ModelSerializer):
    class Meta:
        model = SillyBlog
        
#
# access rules - filters
#
#
def api_list_records(request):
    """ filters
    . range
    . authorization
    . searchParams like, subject__icontains = 'test'
    """
    queryset = SillyBlog.objects.all()
    return queryset
    
#
# require - read acces
# require - write access
# require - owner ship
# require - delete access
# 
def api_get_record(pk):    
    try:
        return SillyBlog.objects.get(pk=pk)
    except SillyBlog.DoesNotExist:
        return api_new_record()
    
def api_new_record():
    return SillyBlog()
    
def api_save_record(record, data):
    return api_save_new(record, data) if record.id else api_update_record(record, data)
    
def api_save_new(record, data):
    form = _validate_record(record, data)
    if form.is_valid():
        form.save()
        return ""
    return {'errors': form.errors}
        
def api_update_record(record, data):
    form = _validate_record(record, data)
    if form.is_valid():
        form.save()
        return ""
    return {'errors': form.errors}

def _validate_record(record, data):
    form = SillyBlogForm(data, instance=record)
    #
    # record validator
    #
    return form
    
#
# validator
#    
from django import forms

class SillyBlogForm(forms.ModelForm):
    class Meta:
        model = SillyBlog
        #fields = (...)
        

ajax2/templates/ajax2/base.html
{% load staticfiles %}
{% static 'ajax2' as static_dir %}

<!doctype html>
<html>
<head>
<script src="{{ static_dir }}/jquery-1.10.2.min.js"></script>
{% block jscripts %}

{% endblock %}
</head>
<body>
<h2> Ajax Demo</h2>
<div id="content">
{% block content %}

{% endblock %}
</div>
</body>
</html>

ajax2/templates/ajax2/editor.html
{% extends 'ajax2/base.html' %}

{% block content %}
<form action="" method="post">
{% csrf_token %} 
    <input type="hidden" name="id" id="blog_id" value="{{ blog.id|default_if_none:"90" }}">
    
    <div class="field-row">
        <label>Subject:</label> <input type="text" id="id_subject" name="subject" value="{{ blog.subject }}">
        <p><span id="blog-subject"></span></p>
    </div>
    <div class="field-row">
        <lable>Body:</lable> <textarea id="id_body" name="body" rows="6" cols="40">{{ blog.body }}</textarea>
        <p><span id="blog-body"></span></p>
    </div>
    
    <hr>
    
    <a href="#" id="save-blog">Save</a> | 
    <a href="{% url 'ajax2:list-record' %}">Back to list</a>
    
    <p><span id="server-message"></span></p>
    
</form>    
    
<script>

{% comment %}
    page must load csrf-token, which will also be transported via cookies
{% endcomment %}

// using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
function sameOrigin(url) {
    // test that a given url is a same-origin URL
    // url could be relative or scheme relative or absolute
    var host = document.location.host; // host + port
    var protocol = document.location.protocol;
    var sr_origin = '//' + host;
    var origin = protocol + sr_origin;
    // Allow absolute or scheme relative URLs to same origin
    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
        // or any other URL that isn't scheme relative or absolute i.e relative.
        !(/^(\/\/|http:|https:).*/.test(url));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
            // Send the token to same-origin, relative URLs only.
            // Send the token only if the method warrants CSRF protection
            // Using the CSRFToken value acquired earlier
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});


function saveRecord() {
    var url, blog_id, data;
    
    url = "{% url 'ajax2:save-record' 0 %}";
    blog_id = $('#blog_id').val();
    blog_id ? (url = url.replace(/\/0\//g, '/'+blog_id+'/')) : null;
    
    data = {subject: $('#id_subject').val(),
            body: $('#id_body').val()
           };
           
    $('#server-message').html("");
    
    $.ajax({
        url: url,
        method: 'POST', 
        data: data
    })
    .done(function(resp, status, xhr) {
        if (resp.errors) {
            var ar = [];
            for (entry in resp.errors) {
                ar.push(entry + ": " + resp.errors[entry].join(', '));
            }
            $('#server-message').html("<pre>\n"+ar.join("<br/>")+"\n</pre>");
            return;
        }
        var ar = []
        ar.push(resp.id);ar.push(resp.subject);ar.push(resp.body);
        var out = ar.join("<br/>");
        $('#server-message').html("<pre>\n"+out+"\n</pre>");
        $('#blog_id').val(resp.id);
    })
    .fail(function(xhr, status, error) {
        $('#server-message').html(error);
    });
}

$(document).ready(function() {
    $('#save-blog').click(function() {
        saveRecord();
    });
});

</script>    
{% endblock %}

ajax2/templates/ajax2/ng-records.html
<div id="myctrl" ng-controller="MyRecords">
    <span ng-init="x=1; y=2;"></span>
    <span>{% verbatim %}{ x < y? x: y;}{% endverbatim %}</span>
    <ul>
    <li ng-repeat="record in records">        
    {% verbatim %}
        <a href="javascript:void(0);" ng-click="detail($index, record.id)">{{record.subject}}</a>
        <span id="record-{{record.id}}" style="color:red;"></span>
    {% endverbatim %}
    </li>
    </ul>
    
    <hr>
    {% verbatim %}
    {{zSym}}
    {% endverbatim %}    
</div>


<script>
MyRecords = function($scope, $http) {
    $scope.records = {{ records|safe }};
    
    $scope.detail = function(i, id) {
        var v = $scope.records[i].subject;        
        //$('#record-'+id).html( $scope.records[i].subject );
        angular.element('#record-'+id).html( v );
        $scope.records[i].subject = "xx: " + v;
    }
}

</script>

ajax2/templates/ajax2/ng.html
{% extends 'ajax2/base.html' %}

{% load staticfiles %} {# this is needed any pages need access `static`, even though base.html already loaded it #]

{% block jscripts %}
<script type="text/javascript" src="{% static 'js/libs/angular.min.js' %}"></script>
<script>

/**
 * 
 *
 */
var ngBlog = angular.module('ngBlog', []);

/**
 * value services
 *
 */
ngBlog.value('VERSION', 'version-1.0');

/**
 * data model - angular services are singleton
 *
 */
ngBlog.service('BlogManager', ['$http', '$q', function($http, $q) {
    var baseUrl, services;
    baseUrl = "/ajax2/ng";
    services = {
        blogs: function(cb) {
            $http.get(baseUrl+"/blogs")
            .success(function(data, status, headers, config) {
                console.log(data);
                cb(data);
            })
            .error(function(data, status, headers, config) {
                console.log('error:'+status);
            });
        }
    };
    
    return services;
}]);

ngBlog.controller('blogController', ['$scope', 'BlogManager', function($scope, BlogManager) {
    /**
     * ways to run initialization code
     *
     */
    $scope.blogs = [];
    
    BlogManager.blogs(function(data) {
        $scope.blogs = data;
    });

}]);

function JsCallThingInModules() {
    /**
     * keynote: it is through inject we access module services
     *
     * http://docs.angularjs.org/api/angular.module
     *
     */
    var injector = angular.injector(['ng', 'ngBlog']);
    var manager = injector.get('BlogManager');
    manager.blogs(function(data) {
        var count = data.length;
        console.log('injector: '+count +', version:' + injector.get('VERSION'));
    });

}

$(document).ready(function() {
    JsCallThingInModules();
});

</script>    
{% endblock %}

{% block content %}
<div ng-app="ngBlog">
    <div ng-controller="blogController">
    <ul>
        <li ng-repeat="blog in blogs">
            {% verbatim %} {{blog.subject}} {% endverbatim %}
        </li>
    </ul>
    </div>
</div>
{% endblock %}

ajax2/templates/ajax2/records.html
{% extends 'ajax2/base.html' %}

{% block content %}
<table>
<tr><th>ID</th><th>Subject</th></tr>
{% for record in records %}    
    <tr><td>{{ record.id }}</td><td><a href="{% url 'ajax2:view-record' pk=record.id %}">{{ record.subject }}</a></td></tr>
{% empty %}
    <tr><td>&nbsp;</td><td>search found no records</td></tr>
{% endfor %}
</table>

{% endblock %}