ajax2/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('',
    url(r'^$', 'ajax2.views.list_record', name='list-record'),
    url(r'^(?P<pk>\d+)/$', 'ajax2.views.get_record', name='view-record'),
    url(r'^(?P<pk>\d+)/save/$', 'ajax2.views.save_record', name='save-record'),
    url(r'^ng/$', 'ajax2.views.ng_way', name='ng-way'),
    url(r'^ng/blogs/$', 'ajax2.views.blogs', name='ng-blogs'),
)    

ajax_demo/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('ajax_demo.views',
    url(r'^$', 'index', name='index'),
    url(r'^contacts/$', 'contacts', name='contacts'),
    url(r'^contact/new/$', 'contact_new', name='contact-new'),
    url(r'^contact/contact/save/$', 'contact_save_new', name='contact-save-new'),
    url(r'^contact/(?P<pk>\d+)/$', 'contact_details', name='contact-details'),
    url(r'^contact/(?P<pk>\d+)/edit/$', 'contact_edit', name='contact-edit'),
    url(r'^contact/save$', 'contact_save_edit', name='contact-save'),
    

)

dj_demo_proj/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dj_demo_proj.views.home', name='home'),
    # url(r'^dj_demo_proj/', include('dj_demo_proj.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^polls/', include('polls.urls', namespace='sstar')),
    url(r'^ajax/', include('ajax_demo.urls', namespace='ajax-demo')),
    
    url(r'^ajax2/', include('ajax2.urls', namespace='ajax2')),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    
)

ajax_demo/models.py
""" side notes:
    SillyContact._meta.get_all_field_names()
    SillyContact._meta.get_field('dob')
    
    https://docs.djangoproject.com/en/dev/ref/contrib/csrf/
    
"""

from django.db import models

# Create your models here.
from django.utils import timezone


class SillyContact(models.Model):
    #
    # TODO - add validators
    #
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    dob = models.DateField('date of birth', null=True, default=timezone.now())
    title = models.CharField('job position', max_length=60)
    email = models.EmailField()
    salary = models.DecimalField(null=True, max_digits=18, decimal_places=2)
    
    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)
        
        
import django_filters  
"""
{% block content %}
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter %}
        {{ obj.name }} - ${{ obj.price }}<br />
    {% endfor %}
{% endblock %}
"""      
class SalariedContact(django_filters.FilterSet):
    
    salary = django_filters.NumberFilter(lookup_type='gt')
    last_name = django_filters.CharFilter(lookup_type='icontains')
    
    class Meta:
        model = SillyContact
        fields = ['salary', 'last_name']
        
        

ajax_demo/forms.py
"""
https://docs.djangoproject.com/en/dev/topics/forms/
https://docs.djangoproject.com/en/dev/ref/forms/fields/


    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    dob = models.DateTimeField('date of birth', null=True, default=timezone.now())
    title = models.CharField('job position', max_length=60)
    email = models.EmailField()
    salary = models.DecimalField(null=True, max_digits=18, decimal_places=2)

Core Field options:
    initial
    label
    help_text
    widdget
    localize
    
    required
    
    validators
    error_messages
    
    
Fields:
    ComboField - validate against a list of fields (a field is a validator in django term)
    MultipleValueField
    SplitDateTimeField
    
"""
from django import forms

from django.utils import timezone

class SillyContactForm(forms.Form):
    """
        validate a single field:
            form = SillyContactForm()
            form.fields['first_name'].clean('') -> 'required' error
            form.fields['first_name'].clean('a') -> u'a'
            
    """
    CONTACT_NAME_OPTS = {'min_length': 1, 'max_length': 20}
    
    #id = forms.IntegerField(required=False)
    
    first_name = forms.CharField(help_text='Your First Name', **CONTACT_NAME_OPTS)
    last_name = forms.CharField(**CONTACT_NAME_OPTS)
    
    title = forms.CharField(required=False)
    email = forms.EmailField(required=True, error_messages={'invalid': 'please enter a valid email address', 'required': 'email address cannot be blank'})
    salary = forms.DecimalField(required=False, max_digits=19, decimal_places=2)
    
    dob = forms.DateField(required=False, input_formats=['%m/%d/%y', '%Y-%m-%d'], initial=timezone.now(), error_messages={'invalid': 'invalid dob'})
    

from ajax_demo.models import SillyContact

class ContactForm(forms.ModelForm):
    class Meta:
        model = SillyContact
        fields = ['first_name', 'last_name', 'title', 'email', 'salary', 'dob'] #default is '__all__'
        
        #exlude = [...]
        #
        #
        # widgets, labels, help_texts, error_messages for further customization form display
        #
        #
        
        
    

ajax_demo/scripts/forms.py
from ajax_demo.models import SillyContact
from ajax_demo.forms import SillyContactForm, ContactForm
from django.core.validators import ValidationError

def min10(value):
    if len(value) < 10:
        raise 'Error, min 10'
        
def run():
    form = SillyContactForm()
    dob = form.fields['dob'].clean('01/12/13')
    print dob
    
    try:
        dob = form.fields['dob']        
        dob.clean('14/01/15')
    except ValidationError as e:    
        print e
    
    
    print 'test ModelForm'
    
    request = {
        'first_name': 'Bill',
        'last_name': 'SMith',
        'title': 'doer',
        'email': 'j@x.com',
        'dob': '1999-12-01', 
        'salary': 10000,
    }
    
    #
    # empty form with initial
    #
    form = ContactForm(request)
    print form
    print
    
    #
    # create a contact from request
    #
    contact = SillyContact()
    form = ContactForm(request, instance=contact)
    form.save()
    print contact, contact.id
    print
    
    #
    # create a contact from request, do not save
    #
    contact = SillyContact()
    form = ContactForm(request, instance=contact)
    form.save(commit=False)
    print contact, contact.id
    
    form.first_name = "bill2"
    print 'is valid: ', form.is_valid()
    form.save()
    #
    #form.save_m2m() #need this to commit m2m relation due to previous commit=False
    #
    print contact, contact.first_name, contact.id
    print
    
    #
    # get record for edit /<pk>/
    #
    form = ContactForm(instance=SillyContact.objects.get(pk=1))
    print form
    print form.id
    

ajax_demo/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404


from ajax_demo.models import SillyContact
from ajax_demo.forms import SillyContactForm

def index(request):
    
    return render(request, 'ajax_demo/index.html')
    
def contacts(request):
    contacts = SillyContact.objects.all()
    context = {'contacts': contacts}
    
    return render(request, 'ajax_demo/fragments/contacts.html', context)
    
def contact_new(request):
    """
    show form for entering new record
    """
    initials = {'first_name': 'John', 'last_name': 'Smith', 'email': 'jsmith@j.com'}
    context = {'contact_form': SillyContactForm(initial=initials, prefix='silly')}
    
    return render(request, 'ajax_demo/fragments/contact_form.html', context)
    
def contact_save_new(request):
    """
    save new - can be combined into 'save edit'
    """
    #print 'method: ', request.method #GET, POST ... in upper case
    #print 'is_secure: ', request.is_secure()
    #print 'is_ajax: ', request.is_ajax()
    
    if request.method != 'POST':
        return HttpResponseRedirect( reverse('ajax-demo:contact-new') )
        
    form = SillyContactForm(request.POST, prefix='silly') #data, is_valid(), is_bound, is_multipart, cleaned_data, changed_data, prefix ...
    #print 'is-bound: ', form.is_bound
    
    if not form.is_valid():
        context = {'contact_form': form}
        return render(request, 'ajax_demo/fragments/contact_form.html', context)
        
    #for f in form.fields:
    #    print f
    
    #cleaned_data dict is just good for create record
    silly, created = SillyContact.objects.get_or_create(**form.cleaned_data)

    return HttpResponseRedirect( reverse('ajax-demo:contact-details', kwargs={'pk': silly.id}) )

    
def contact_details(request, pk):
    """
    show detail 
    """
    silly = SillyContact.objects.get(pk=pk)
    
    data = {}
    fields = silly._meta.get_all_field_names()
    for field in fields:
        data[field] = getattr(silly, field)
        
    context = {'contact_form': SillyContactForm(initial=data, prefix='silly'),
               'contact_record': silly}
    
    return render(request, 'ajax_demo/fragments/contact_detail.html', context)
    
def contact_edit(request, pk):
    """
    show form for edit
    """
    silly = SillyContact.objects.get(pk=pk)
    
    data = {}
    fields = silly._meta.get_all_field_names()
    for field in fields:
        data[field] = getattr(silly, field)
        
    context = {'contact_form': SillyContactForm(initial=data, prefix='silly'), 'contact_record': silly}
    
    return render(request, 'ajax_demo/fragments/contact_edit.html', context)
    
def contact_save_edit(request):
    """
    save edit - it is not DRY but we do need to distinguish UPDATE from CREATE for handling UPDATE logic
    """
    if request.method != 'POST':
        return HttpResponseForbidden()
        
    pk = request.POST.get('id', None)
    if not pk:
        return HttpResponseForbidden()
    
    silly = get_object_or_404(SillyContact, pk=pk)
    
    form = SillyContactForm(request.POST, prefix='silly') 
    if not form.is_valid():
        context = {'contact_form': form, 'contact_record': silly}
        return render(request, 'ajax_demo/fragments/contact_edit.html', context)

    #
    #save - would be nice if django provides silly.save(**form.cleaned_data)
    #
    [setattr(silly, k, v) for k, v in form.cleaned_data.items()]
    silly.save()
    
    return redirect('ajax-demo:contact-details', pk=pk)

    
        

ajax_demo/templates/ajax_demo/fragments/contact_detail.html
<form action="{% url 'ajax-demo:contact-edit' pk=contact_record.id %}" method="post">
{% include 'ajax_demo/fragments/contact_form_snippet.html' with form=contact_form %}
<p><input type="submit" value="Edit This Contact" /></p>
</form>

ajax_demo/templates/ajax_demo/fragments/contact_edit.html
<form action="{% url 'ajax-demo:contact-save' %}" method="post">
<input type="hidden" name="id" value="{{ contact_record.id }}" />
{% include 'ajax_demo/fragments/contact_form_snippet.html' with form=contact_form %}
<p><input type="submit" value="Save" /></p>
</form>

ajax_demo/templates/ajax_demo/fragments/contact_form.html
<form action="{% url 'ajax-demo:contact-save-new' %}" method="post">
{% include 'ajax_demo/fragments/contact_form_snippet.html' with form=contact_form %}
<p><input type="submit" value="Save Contact" /></p>
</form>

ajax_demo/templates/ajax_demo/fragments/contact_form_snippet.html
{% comment %}
args - form, to use different context, use include with form=the-form
{% endcomment %}

{% csrf_token %}
{{ form.non_field_errors }}
<div class="field contact-edit">
    {{ form.first_name.errors }}
    <label for="id_first_name">First Name:</label>
    {{ form.first_name }} {{ form.first_name.help_text }}
</div>
<div class="field contact-edit">
    {{ form.last_name.errors }}
    <label for="id_last_name">Last Name:</label>
    {{ form.last_name }} {{ form.last_name.help_text }}
</div>
<div class="field contact-edit">    
    <label for="id_email">Email:</label>
    {{ form.email }} {{ form.email.help_text }} 
    {% for error in form.email.errors %}
        {{ error }}
    {% empty %}
        .
    {% endfor %}
</div>

<div class="field contact-edit">
    {{ form.title.errors }}
    <label for="id_title">Title:</label>
    {{ form.title }} {{ form.title.help_text }}
</div>
<div class="field contact-edit">    
    <label for="id_dob">Date of Birth:</label>
    {{ form.dob }} {{ form.dob.help_text }} 
    {% for error in form.dob.errors %}
        {{ error }}
    {% empty %}
        .
    {% endfor %}
</div>
<div class="field contact-edit">
    {{ form.salary.errors }}
    <label for="id_salary">Salary:</label>
    {{ form.salary }} {{ form.salary.help_text }}
</div>

<style>
div.contact-edit > label {
    display: inline-block;
    width: 200px;
}
</style>

ajax_demo/templates/ajax_demo/fragments/contact_new_ok.html
new contact saved.

ajax_demo/templates/ajax_demo/fragments/contacts.html
<h2>Contacts</h2>
{% for contact in contacts %}    
    Search Found {{ contacts|length }} record{{ contacts|pluralize }} <br/>
    <ul>
        <li>{{ contact.first_name }} {{ contact.last_name }}</li>
    </ul>
{% empty %}
    <b>found no records</b>
{% endfor %}
<hr/>
<a href="{% url 'ajax-demo:contact-new' %}">New Contact</a>

<script>
    //alert('found {{ contacts|length }} record{{ contacts|pluralize }}');
</script>